/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import su.nsk.iae.tempor.tempor.Rel;
import su.nsk.iae.tempor.tempor.SentenceDeclaration;
import su.nsk.iae.tempor.tempor.TemporPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.impl.RelImpl#getRel <em>Rel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelImpl extends RelReaImpl implements Rel
{
  /**
   * The cached value of the '{@link #getRel() <em>Rel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRel()
   * @generated
   * @ordered
   */
  protected SentenceDeclaration rel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TemporPackage.Literals.REL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SentenceDeclaration getRel()
  {
    if (rel != null && rel.eIsProxy())
    {
      InternalEObject oldRel = (InternalEObject)rel;
      rel = (SentenceDeclaration)eResolveProxy(oldRel);
      if (rel != oldRel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TemporPackage.REL__REL, oldRel, rel));
      }
    }
    return rel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SentenceDeclaration basicGetRel()
  {
    return rel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRel(SentenceDeclaration newRel)
  {
    SentenceDeclaration oldRel = rel;
    rel = newRel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporPackage.REL__REL, oldRel, rel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TemporPackage.REL__REL:
        if (resolve) return getRel();
        return basicGetRel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TemporPackage.REL__REL:
        setRel((SentenceDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TemporPackage.REL__REL:
        setRel((SentenceDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TemporPackage.REL__REL:
        return rel != null;
    }
    return super.eIsSet(featureID);
  }

} //RelImpl
