/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import su.nsk.iae.tempor.tempor.DelFin;
import su.nsk.iae.tempor.tempor.Rea;
import su.nsk.iae.tempor.tempor.RelRea;
import su.nsk.iae.tempor.tempor.TemporPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rel Rea</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.impl.RelReaImpl#getReaction <em>Reaction</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.impl.RelReaImpl#getDelay_final <em>Delay final</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelReaImpl extends MinimalEObjectImpl.Container implements RelRea
{
  /**
   * The cached value of the '{@link #getReaction() <em>Reaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReaction()
   * @generated
   * @ordered
   */
  protected Rea reaction;

  /**
   * The cached value of the '{@link #getDelay_final() <em>Delay final</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDelay_final()
   * @generated
   * @ordered
   */
  protected DelFin delay_final;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelReaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TemporPackage.Literals.REL_REA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rea getReaction()
  {
    return reaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReaction(Rea newReaction, NotificationChain msgs)
  {
    Rea oldReaction = reaction;
    reaction = newReaction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TemporPackage.REL_REA__REACTION, oldReaction, newReaction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReaction(Rea newReaction)
  {
    if (newReaction != reaction)
    {
      NotificationChain msgs = null;
      if (reaction != null)
        msgs = ((InternalEObject)reaction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TemporPackage.REL_REA__REACTION, null, msgs);
      if (newReaction != null)
        msgs = ((InternalEObject)newReaction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TemporPackage.REL_REA__REACTION, null, msgs);
      msgs = basicSetReaction(newReaction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporPackage.REL_REA__REACTION, newReaction, newReaction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DelFin getDelay_final()
  {
    return delay_final;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDelay_final(DelFin newDelay_final, NotificationChain msgs)
  {
    DelFin oldDelay_final = delay_final;
    delay_final = newDelay_final;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TemporPackage.REL_REA__DELAY_FINAL, oldDelay_final, newDelay_final);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDelay_final(DelFin newDelay_final)
  {
    if (newDelay_final != delay_final)
    {
      NotificationChain msgs = null;
      if (delay_final != null)
        msgs = ((InternalEObject)delay_final).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TemporPackage.REL_REA__DELAY_FINAL, null, msgs);
      if (newDelay_final != null)
        msgs = ((InternalEObject)newDelay_final).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TemporPackage.REL_REA__DELAY_FINAL, null, msgs);
      msgs = basicSetDelay_final(newDelay_final, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporPackage.REL_REA__DELAY_FINAL, newDelay_final, newDelay_final));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TemporPackage.REL_REA__REACTION:
        return basicSetReaction(null, msgs);
      case TemporPackage.REL_REA__DELAY_FINAL:
        return basicSetDelay_final(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TemporPackage.REL_REA__REACTION:
        return getReaction();
      case TemporPackage.REL_REA__DELAY_FINAL:
        return getDelay_final();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TemporPackage.REL_REA__REACTION:
        setReaction((Rea)newValue);
        return;
      case TemporPackage.REL_REA__DELAY_FINAL:
        setDelay_final((DelFin)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TemporPackage.REL_REA__REACTION:
        setReaction((Rea)null);
        return;
      case TemporPackage.REL_REA__DELAY_FINAL:
        setDelay_final((DelFin)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TemporPackage.REL_REA__REACTION:
        return reaction != null;
      case TemporPackage.REL_REA__DELAY_FINAL:
        return delay_final != null;
    }
    return super.eIsSet(featureID);
  }

} //RelReaImpl
