/*
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TemporStandaloneSetup extends TemporStandaloneSetupGenerated {

	public static void doSetup() {
		new TemporStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
