/*
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TemporRuntimeModule extends AbstractTemporRuntimeModule {
}
