/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import su.nsk.iae.tempor.tempor.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see su.nsk.iae.tempor.tempor.TemporPackage
 * @generated
 */
public class TemporAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static TemporPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TemporAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = TemporPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TemporSwitch<Adapter> modelSwitch =
    new TemporSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseDeclVarInput(DeclVarInput object)
      {
        return createDeclVarInputAdapter();
      }
      @Override
      public Adapter caseDeclVarOutput(DeclVarOutput object)
      {
        return createDeclVarOutputAdapter();
      }
      @Override
      public Adapter caseVarDeclaration(VarDeclaration object)
      {
        return createVarDeclarationAdapter();
      }
      @Override
      public Adapter caseSentDeclaration(SentDeclaration object)
      {
        return createSentDeclarationAdapter();
      }
      @Override
      public Adapter caseSentenceDeclaration(SentenceDeclaration object)
      {
        return createSentenceDeclarationAdapter();
      }
      @Override
      public Adapter caseExpression(Expression object)
      {
        return createExpressionAdapter();
      }
      @Override
      public Adapter caseXorExpression(XorExpression object)
      {
        return createXorExpressionAdapter();
      }
      @Override
      public Adapter caseAndExpression(AndExpression object)
      {
        return createAndExpressionAdapter();
      }
      @Override
      public Adapter caseCompExpression(CompExpression object)
      {
        return createCompExpressionAdapter();
      }
      @Override
      public Adapter caseEquExpression(EquExpression object)
      {
        return createEquExpressionAdapter();
      }
      @Override
      public Adapter caseUnExpression(UnExpression object)
      {
        return createUnExpressionAdapter();
      }
      @Override
      public Adapter caseTauExpression(TauExpression object)
      {
        return createTauExpressionAdapter();
      }
      @Override
      public Adapter caseTimeLiteral(TimeLiteral object)
      {
        return createTimeLiteralAdapter();
      }
      @Override
      public Adapter casePrimaryExpression(PrimaryExpression object)
      {
        return createPrimaryExpressionAdapter();
      }
      @Override
      public Adapter caseReqDeclaration(ReqDeclaration object)
      {
        return createReqDeclarationAdapter();
      }
      @Override
      public Adapter caseRequirement(Requirement object)
      {
        return createRequirementAdapter();
      }
      @Override
      public Adapter caseTrig(Trig object)
      {
        return createTrigAdapter();
      }
      @Override
      public Adapter caseInv(Inv object)
      {
        return createInvAdapter();
      }
      @Override
      public Adapter caseInv_always(Inv_always object)
      {
        return createInv_alwaysAdapter();
      }
      @Override
      public Adapter caseRelRea(RelRea object)
      {
        return createRelReaAdapter();
      }
      @Override
      public Adapter caseRea(Rea object)
      {
        return createReaAdapter();
      }
      @Override
      public Adapter caseDelFin(DelFin object)
      {
        return createDelFinAdapter();
      }
      @Override
      public Adapter caseDelay(Delay object)
      {
        return createDelayAdapter();
      }
      @Override
      public Adapter caseRel(Rel object)
      {
        return createRelAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.DeclVarInput <em>Decl Var Input</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.DeclVarInput
   * @generated
   */
  public Adapter createDeclVarInputAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.DeclVarOutput <em>Decl Var Output</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.DeclVarOutput
   * @generated
   */
  public Adapter createDeclVarOutputAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.VarDeclaration <em>Var Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.VarDeclaration
   * @generated
   */
  public Adapter createVarDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.SentDeclaration <em>Sent Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.SentDeclaration
   * @generated
   */
  public Adapter createSentDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.SentenceDeclaration <em>Sentence Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.SentenceDeclaration
   * @generated
   */
  public Adapter createSentenceDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Expression
   * @generated
   */
  public Adapter createExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.XorExpression <em>Xor Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.XorExpression
   * @generated
   */
  public Adapter createXorExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.AndExpression <em>And Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.AndExpression
   * @generated
   */
  public Adapter createAndExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.CompExpression <em>Comp Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.CompExpression
   * @generated
   */
  public Adapter createCompExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.EquExpression <em>Equ Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.EquExpression
   * @generated
   */
  public Adapter createEquExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.UnExpression <em>Un Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.UnExpression
   * @generated
   */
  public Adapter createUnExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.TauExpression <em>Tau Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.TauExpression
   * @generated
   */
  public Adapter createTauExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.TimeLiteral <em>Time Literal</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.TimeLiteral
   * @generated
   */
  public Adapter createTimeLiteralAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.PrimaryExpression <em>Primary Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.PrimaryExpression
   * @generated
   */
  public Adapter createPrimaryExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.ReqDeclaration <em>Req Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.ReqDeclaration
   * @generated
   */
  public Adapter createReqDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Requirement <em>Requirement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Requirement
   * @generated
   */
  public Adapter createRequirementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Trig <em>Trig</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Trig
   * @generated
   */
  public Adapter createTrigAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Inv <em>Inv</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Inv
   * @generated
   */
  public Adapter createInvAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Inv_always <em>Inv always</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Inv_always
   * @generated
   */
  public Adapter createInv_alwaysAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.RelRea <em>Rel Rea</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.RelRea
   * @generated
   */
  public Adapter createRelReaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Rea <em>Rea</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Rea
   * @generated
   */
  public Adapter createReaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.DelFin <em>Del Fin</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.DelFin
   * @generated
   */
  public Adapter createDelFinAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Delay <em>Delay</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Delay
   * @generated
   */
  public Adapter createDelayAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link su.nsk.iae.tempor.tempor.Rel <em>Rel</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see su.nsk.iae.tempor.tempor.Rel
   * @generated
   */
  public Adapter createRelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //TemporAdapterFactory
