/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decl Var Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.DeclVarInput#getVarDecls <em>Var Decls</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getDeclVarInput()
 * @model
 * @generated
 */
public interface DeclVarInput extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Decls</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.tempor.tempor.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Decls</em>' containment reference list.
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getDeclVarInput_VarDecls()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getVarDecls();

} // DeclVarInput
