/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delay</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.Delay#getDel <em>Del</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getDelay()
 * @model
 * @generated
 */
public interface Delay extends EObject
{
  /**
   * Returns the value of the '<em><b>Del</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Del</em>' reference.
   * @see #setDel(SentenceDeclaration)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getDelay_Del()
   * @model
   * @generated
   */
  SentenceDeclaration getDel();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.Delay#getDel <em>Del</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Del</em>' reference.
   * @see #getDel()
   * @generated
   */
  void setDel(SentenceDeclaration value);

} // Delay
