/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.Model#getDeclVarInput <em>Decl Var Input</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.Model#getDeclVarOutput <em>Decl Var Output</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.Model#getSentDeclaration <em>Sent Declaration</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.Model#getReqDeclaration <em>Req Declaration</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Decl Var Input</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.tempor.tempor.DeclVarInput}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl Var Input</em>' containment reference list.
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getModel_DeclVarInput()
   * @model containment="true"
   * @generated
   */
  EList<DeclVarInput> getDeclVarInput();

  /**
   * Returns the value of the '<em><b>Decl Var Output</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.tempor.tempor.DeclVarOutput}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl Var Output</em>' containment reference list.
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getModel_DeclVarOutput()
   * @model containment="true"
   * @generated
   */
  EList<DeclVarOutput> getDeclVarOutput();

  /**
   * Returns the value of the '<em><b>Sent Declaration</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.tempor.tempor.SentDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sent Declaration</em>' containment reference list.
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getModel_SentDeclaration()
   * @model containment="true"
   * @generated
   */
  EList<SentDeclaration> getSentDeclaration();

  /**
   * Returns the value of the '<em><b>Req Declaration</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.tempor.tempor.ReqDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req Declaration</em>' containment reference list.
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getModel_ReqDeclaration()
   * @model containment="true"
   * @generated
   */
  EList<ReqDeclaration> getReqDeclaration();

} // Model
