/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rea</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.Rea#getRea <em>Rea</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getRea()
 * @model
 * @generated
 */
public interface Rea extends RelRea
{
  /**
   * Returns the value of the '<em><b>Rea</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rea</em>' reference.
   * @see #setRea(SentenceDeclaration)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getRea_Rea()
   * @model
   * @generated
   */
  SentenceDeclaration getRea();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.Rea#getRea <em>Rea</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rea</em>' reference.
   * @see #getRea()
   * @generated
   */
  void setRea(SentenceDeclaration value);

} // Rea
