/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Req Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.ReqDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.ReqDeclaration#getRequirement <em>Requirement</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getReqDeclaration()
 * @model
 * @generated
 */
public interface ReqDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getReqDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.ReqDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Requirement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement</em>' containment reference.
   * @see #setRequirement(Requirement)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getReqDeclaration_Requirement()
   * @model containment="true"
   * @generated
   */
  Requirement getRequirement();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.ReqDeclaration#getRequirement <em>Requirement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirement</em>' containment reference.
   * @see #getRequirement()
   * @generated
   */
  void setRequirement(Requirement value);

} // ReqDeclaration
