/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sent Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.SentDeclaration#getDeclarationName <em>Declaration Name</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.SentDeclaration#getSentenceDeclaration <em>Sentence Declaration</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getSentDeclaration()
 * @model
 * @generated
 */
public interface SentDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration Name</em>' attribute.
   * @see #setDeclarationName(String)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getSentDeclaration_DeclarationName()
   * @model
   * @generated
   */
  String getDeclarationName();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.SentDeclaration#getDeclarationName <em>Declaration Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration Name</em>' attribute.
   * @see #getDeclarationName()
   * @generated
   */
  void setDeclarationName(String value);

  /**
   * Returns the value of the '<em><b>Sentence Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentence Declaration</em>' containment reference.
   * @see #setSentenceDeclaration(SentenceDeclaration)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getSentDeclaration_SentenceDeclaration()
   * @model containment="true"
   * @generated
   */
  SentenceDeclaration getSentenceDeclaration();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.SentDeclaration#getSentenceDeclaration <em>Sentence Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sentence Declaration</em>' containment reference.
   * @see #getSentenceDeclaration()
   * @generated
   */
  void setSentenceDeclaration(SentenceDeclaration value);

} // SentDeclaration
