/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see su.nsk.iae.tempor.tempor.TemporFactory
 * @model kind="package"
 * @generated
 */
public interface TemporPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tempor";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.nsk.su/iae/tempor/Tempor";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tempor";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TemporPackage eINSTANCE = su.nsk.iae.tempor.tempor.impl.TemporPackageImpl.init();

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.ModelImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Decl Var Input</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECL_VAR_INPUT = 0;

  /**
   * The feature id for the '<em><b>Decl Var Output</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECL_VAR_OUTPUT = 1;

  /**
   * The feature id for the '<em><b>Sent Declaration</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SENT_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Req Declaration</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REQ_DECLARATION = 3;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.DeclVarInputImpl <em>Decl Var Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.DeclVarInputImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDeclVarInput()
   * @generated
   */
  int DECL_VAR_INPUT = 1;

  /**
   * The feature id for the '<em><b>Var Decls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_VAR_INPUT__VAR_DECLS = 0;

  /**
   * The number of structural features of the '<em>Decl Var Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_VAR_INPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.DeclVarOutputImpl <em>Decl Var Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.DeclVarOutputImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDeclVarOutput()
   * @generated
   */
  int DECL_VAR_OUTPUT = 2;

  /**
   * The feature id for the '<em><b>Var Decls</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_VAR_OUTPUT__VAR_DECLS = 0;

  /**
   * The number of structural features of the '<em>Decl Var Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_VAR_OUTPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.VarDeclarationImpl <em>Var Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.VarDeclarationImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getVarDeclaration()
   * @generated
   */
  int VAR_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__TYPE = 1;

  /**
   * The number of structural features of the '<em>Var Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.SentDeclarationImpl <em>Sent Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.SentDeclarationImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getSentDeclaration()
   * @generated
   */
  int SENT_DECLARATION = 4;

  /**
   * The feature id for the '<em><b>Declaration Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENT_DECLARATION__DECLARATION_NAME = 0;

  /**
   * The feature id for the '<em><b>Sentence Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENT_DECLARATION__SENTENCE_DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Sent Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENT_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.SentenceDeclarationImpl <em>Sentence Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.SentenceDeclarationImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getSentenceDeclaration()
   * @generated
   */
  int SENTENCE_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Logic Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_DECLARATION__LOGIC_EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Sentence Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.ExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OR_OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.XorExpressionImpl <em>Xor Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.XorExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getXorExpression()
   * @generated
   */
  int XOR_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR_EXPRESSION__LEFT = EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR_EXPRESSION__OR_OP = EXPRESSION__OR_OP;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR_EXPRESSION__RIGHT = EXPRESSION__RIGHT;

  /**
   * The number of structural features of the '<em>Xor Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.AndExpressionImpl <em>And Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.AndExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getAndExpression()
   * @generated
   */
  int AND_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__LEFT = XOR_EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__OR_OP = XOR_EXPRESSION__OR_OP;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__RIGHT = XOR_EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>And Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__AND_OP = XOR_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>And Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION_FEATURE_COUNT = XOR_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.CompExpressionImpl <em>Comp Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.CompExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getCompExpression()
   * @generated
   */
  int COMP_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__LEFT = AND_EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__OR_OP = AND_EXPRESSION__OR_OP;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__RIGHT = AND_EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>And Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__AND_OP = AND_EXPRESSION__AND_OP;

  /**
   * The feature id for the '<em><b>Comp Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__COMP_OP = AND_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comp Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION_FEATURE_COUNT = AND_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.EquExpressionImpl <em>Equ Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.EquExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getEquExpression()
   * @generated
   */
  int EQU_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION__LEFT = COMP_EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION__OR_OP = COMP_EXPRESSION__OR_OP;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION__RIGHT = COMP_EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>And Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION__AND_OP = COMP_EXPRESSION__AND_OP;

  /**
   * The feature id for the '<em><b>Comp Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION__COMP_OP = COMP_EXPRESSION__COMP_OP;

  /**
   * The feature id for the '<em><b>Equ Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION__EQU_OP = COMP_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Equ Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_EXPRESSION_FEATURE_COUNT = COMP_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.UnExpressionImpl <em>Un Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.UnExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getUnExpression()
   * @generated
   */
  int UN_EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__LEFT = EQU_EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__OR_OP = EQU_EXPRESSION__OR_OP;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__RIGHT = EQU_EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>And Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__AND_OP = EQU_EXPRESSION__AND_OP;

  /**
   * The feature id for the '<em><b>Comp Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__COMP_OP = EQU_EXPRESSION__COMP_OP;

  /**
   * The feature id for the '<em><b>Equ Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__EQU_OP = EQU_EXPRESSION__EQU_OP;

  /**
   * The feature id for the '<em><b>Un Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION__UN_OP = EQU_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Un Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UN_EXPRESSION_FEATURE_COUNT = EQU_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.TauExpressionImpl <em>Tau Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.TauExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getTauExpression()
   * @generated
   */
  int TAU_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAU_EXPRESSION__TIME = 0;

  /**
   * The number of structural features of the '<em>Tau Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAU_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.TimeLiteralImpl <em>Time Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.TimeLiteralImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getTimeLiteral()
   * @generated
   */
  int TIME_LITERAL = 13;

  /**
   * The feature id for the '<em><b>Interval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_LITERAL__INTERVAL = 0;

  /**
   * The number of structural features of the '<em>Time Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.PrimaryExpressionImpl <em>Primary Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.PrimaryExpressionImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getPrimaryExpression()
   * @generated
   */
  int PRIMARY_EXPRESSION = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__LEFT = UN_EXPRESSION__LEFT;

  /**
   * The feature id for the '<em><b>Or Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__OR_OP = UN_EXPRESSION__OR_OP;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__RIGHT = UN_EXPRESSION__RIGHT;

  /**
   * The feature id for the '<em><b>And Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__AND_OP = UN_EXPRESSION__AND_OP;

  /**
   * The feature id for the '<em><b>Comp Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__COMP_OP = UN_EXPRESSION__COMP_OP;

  /**
   * The feature id for the '<em><b>Equ Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__EQU_OP = UN_EXPRESSION__EQU_OP;

  /**
   * The feature id for the '<em><b>Un Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__UN_OP = UN_EXPRESSION__UN_OP;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__NAME = UN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__CONSTANT = UN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Tau</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__TAU = UN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Nest Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__NEST_EXPR = UN_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Primary Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION_FEATURE_COUNT = UN_EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.ReqDeclarationImpl <em>Req Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.ReqDeclarationImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getReqDeclaration()
   * @generated
   */
  int REQ_DECLARATION = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Requirement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_DECLARATION__REQUIREMENT = 1;

  /**
   * The number of structural features of the '<em>Req Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQ_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.RequirementImpl <em>Requirement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.RequirementImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRequirement()
   * @generated
   */
  int REQUIREMENT = 16;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__TRIGGER = 0;

  /**
   * The feature id for the '<em><b>Invariant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__INVARIANT = 1;

  /**
   * The number of structural features of the '<em>Requirement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.TrigImpl <em>Trig</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.TrigImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getTrig()
   * @generated
   */
  int TRIG = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIG__NAME = 0;

  /**
   * The feature id for the '<em><b>Invariant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIG__INVARIANT = 1;

  /**
   * The feature id for the '<em><b>Release reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIG__RELEASE_REACTION = 2;

  /**
   * The feature id for the '<em><b>Delay final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIG__DELAY_FINAL = 3;

  /**
   * The number of structural features of the '<em>Trig</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIG_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.InvImpl <em>Inv</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.InvImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getInv()
   * @generated
   */
  int INV = 18;

  /**
   * The feature id for the '<em><b>Inv</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV__INV = 0;

  /**
   * The feature id for the '<em><b>Delay final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV__DELAY_FINAL = 1;

  /**
   * The feature id for the '<em><b>Release reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV__RELEASE_REACTION = 2;

  /**
   * The number of structural features of the '<em>Inv</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.Inv_alwaysImpl <em>Inv always</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.Inv_alwaysImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getInv_always()
   * @generated
   */
  int INV_ALWAYS = 19;

  /**
   * The feature id for the '<em><b>Inv</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV_ALWAYS__INV = 0;

  /**
   * The feature id for the '<em><b>Release reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV_ALWAYS__RELEASE_REACTION = 1;

  /**
   * The number of structural features of the '<em>Inv always</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INV_ALWAYS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.RelReaImpl <em>Rel Rea</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.RelReaImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRelRea()
   * @generated
   */
  int REL_REA = 20;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_REA__REACTION = 0;

  /**
   * The feature id for the '<em><b>Delay final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_REA__DELAY_FINAL = 1;

  /**
   * The number of structural features of the '<em>Rel Rea</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_REA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.ReaImpl <em>Rea</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.ReaImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRea()
   * @generated
   */
  int REA = 21;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REA__REACTION = REL_REA__REACTION;

  /**
   * The feature id for the '<em><b>Delay final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REA__DELAY_FINAL = REL_REA__DELAY_FINAL;

  /**
   * The feature id for the '<em><b>Rea</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REA__REA = REL_REA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rea</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REA_FEATURE_COUNT = REL_REA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.DelFinImpl <em>Del Fin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.DelFinImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDelFin()
   * @generated
   */
  int DEL_FIN = 22;

  /**
   * The feature id for the '<em><b>Delay</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEL_FIN__DELAY = 0;

  /**
   * The feature id for the '<em><b>Fin</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEL_FIN__FIN = 1;

  /**
   * The feature id for the '<em><b>Imm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEL_FIN__IMM = 2;

  /**
   * The number of structural features of the '<em>Del Fin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEL_FIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.DelayImpl <em>Delay</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.DelayImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDelay()
   * @generated
   */
  int DELAY = 23;

  /**
   * The feature id for the '<em><b>Del</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAY__DEL = 0;

  /**
   * The number of structural features of the '<em>Delay</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.impl.RelImpl <em>Rel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.impl.RelImpl
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRel()
   * @generated
   */
  int REL = 24;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL__REACTION = REL_REA__REACTION;

  /**
   * The feature id for the '<em><b>Delay final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL__DELAY_FINAL = REL_REA__DELAY_FINAL;

  /**
   * The feature id for the '<em><b>Rel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL__REL = REL_REA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_FEATURE_COUNT = REL_REA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.EquOperator <em>Equ Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.EquOperator
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getEquOperator()
   * @generated
   */
  int EQU_OPERATOR = 25;

  /**
   * The meta object id for the '{@link su.nsk.iae.tempor.tempor.CompOperator <em>Comp Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see su.nsk.iae.tempor.tempor.CompOperator
   * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getCompOperator()
   * @generated
   */
  int COMP_OPERATOR = 26;


  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see su.nsk.iae.tempor.tempor.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link su.nsk.iae.tempor.tempor.Model#getDeclVarInput <em>Decl Var Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Decl Var Input</em>'.
   * @see su.nsk.iae.tempor.tempor.Model#getDeclVarInput()
   * @see #getModel()
   * @generated
   */
  EReference getModel_DeclVarInput();

  /**
   * Returns the meta object for the containment reference list '{@link su.nsk.iae.tempor.tempor.Model#getDeclVarOutput <em>Decl Var Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Decl Var Output</em>'.
   * @see su.nsk.iae.tempor.tempor.Model#getDeclVarOutput()
   * @see #getModel()
   * @generated
   */
  EReference getModel_DeclVarOutput();

  /**
   * Returns the meta object for the containment reference list '{@link su.nsk.iae.tempor.tempor.Model#getSentDeclaration <em>Sent Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sent Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.Model#getSentDeclaration()
   * @see #getModel()
   * @generated
   */
  EReference getModel_SentDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link su.nsk.iae.tempor.tempor.Model#getReqDeclaration <em>Req Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Req Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.Model#getReqDeclaration()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ReqDeclaration();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.DeclVarInput <em>Decl Var Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl Var Input</em>'.
   * @see su.nsk.iae.tempor.tempor.DeclVarInput
   * @generated
   */
  EClass getDeclVarInput();

  /**
   * Returns the meta object for the containment reference list '{@link su.nsk.iae.tempor.tempor.DeclVarInput#getVarDecls <em>Var Decls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var Decls</em>'.
   * @see su.nsk.iae.tempor.tempor.DeclVarInput#getVarDecls()
   * @see #getDeclVarInput()
   * @generated
   */
  EReference getDeclVarInput_VarDecls();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.DeclVarOutput <em>Decl Var Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl Var Output</em>'.
   * @see su.nsk.iae.tempor.tempor.DeclVarOutput
   * @generated
   */
  EClass getDeclVarOutput();

  /**
   * Returns the meta object for the containment reference list '{@link su.nsk.iae.tempor.tempor.DeclVarOutput#getVarDecls <em>Var Decls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var Decls</em>'.
   * @see su.nsk.iae.tempor.tempor.DeclVarOutput#getVarDecls()
   * @see #getDeclVarOutput()
   * @generated
   */
  EReference getDeclVarOutput_VarDecls();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.VarDeclaration <em>Var Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.VarDeclaration
   * @generated
   */
  EClass getVarDeclaration();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.VarDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see su.nsk.iae.tempor.tempor.VarDeclaration#getName()
   * @see #getVarDeclaration()
   * @generated
   */
  EAttribute getVarDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.VarDeclaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see su.nsk.iae.tempor.tempor.VarDeclaration#getType()
   * @see #getVarDeclaration()
   * @generated
   */
  EAttribute getVarDeclaration_Type();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.SentDeclaration <em>Sent Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sent Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.SentDeclaration
   * @generated
   */
  EClass getSentDeclaration();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.SentDeclaration#getDeclarationName <em>Declaration Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Declaration Name</em>'.
   * @see su.nsk.iae.tempor.tempor.SentDeclaration#getDeclarationName()
   * @see #getSentDeclaration()
   * @generated
   */
  EAttribute getSentDeclaration_DeclarationName();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.SentDeclaration#getSentenceDeclaration <em>Sentence Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sentence Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.SentDeclaration#getSentenceDeclaration()
   * @see #getSentDeclaration()
   * @generated
   */
  EReference getSentDeclaration_SentenceDeclaration();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.SentenceDeclaration <em>Sentence Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sentence Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.SentenceDeclaration
   * @generated
   */
  EClass getSentenceDeclaration();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.SentenceDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see su.nsk.iae.tempor.tempor.SentenceDeclaration#getName()
   * @see #getSentenceDeclaration()
   * @generated
   */
  EAttribute getSentenceDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.SentenceDeclaration#getLogicExpression <em>Logic Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logic Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.SentenceDeclaration#getLogicExpression()
   * @see #getSentenceDeclaration()
   * @generated
   */
  EReference getSentenceDeclaration_LogicExpression();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see su.nsk.iae.tempor.tempor.Expression#getLeft()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.Expression#getOrOp <em>Or Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Or Op</em>'.
   * @see su.nsk.iae.tempor.tempor.Expression#getOrOp()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_OrOp();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see su.nsk.iae.tempor.tempor.Expression#getRight()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Right();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.XorExpression <em>Xor Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xor Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.XorExpression
   * @generated
   */
  EClass getXorExpression();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.AndExpression <em>And Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.AndExpression
   * @generated
   */
  EClass getAndExpression();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.AndExpression#getAndOp <em>And Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>And Op</em>'.
   * @see su.nsk.iae.tempor.tempor.AndExpression#getAndOp()
   * @see #getAndExpression()
   * @generated
   */
  EAttribute getAndExpression_AndOp();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.CompExpression <em>Comp Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comp Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.CompExpression
   * @generated
   */
  EClass getCompExpression();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.CompExpression#getCompOp <em>Comp Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comp Op</em>'.
   * @see su.nsk.iae.tempor.tempor.CompExpression#getCompOp()
   * @see #getCompExpression()
   * @generated
   */
  EAttribute getCompExpression_CompOp();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.EquExpression <em>Equ Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equ Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.EquExpression
   * @generated
   */
  EClass getEquExpression();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.EquExpression#getEquOp <em>Equ Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Equ Op</em>'.
   * @see su.nsk.iae.tempor.tempor.EquExpression#getEquOp()
   * @see #getEquExpression()
   * @generated
   */
  EAttribute getEquExpression_EquOp();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.UnExpression <em>Un Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Un Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.UnExpression
   * @generated
   */
  EClass getUnExpression();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.UnExpression#getUnOp <em>Un Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Un Op</em>'.
   * @see su.nsk.iae.tempor.tempor.UnExpression#getUnOp()
   * @see #getUnExpression()
   * @generated
   */
  EAttribute getUnExpression_UnOp();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.TauExpression <em>Tau Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tau Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.TauExpression
   * @generated
   */
  EClass getTauExpression();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.TauExpression#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see su.nsk.iae.tempor.tempor.TauExpression#getTime()
   * @see #getTauExpression()
   * @generated
   */
  EReference getTauExpression_Time();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.TimeLiteral <em>Time Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Literal</em>'.
   * @see su.nsk.iae.tempor.tempor.TimeLiteral
   * @generated
   */
  EClass getTimeLiteral();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.TimeLiteral#getInterval <em>Interval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Interval</em>'.
   * @see su.nsk.iae.tempor.tempor.TimeLiteral#getInterval()
   * @see #getTimeLiteral()
   * @generated
   */
  EAttribute getTimeLiteral_Interval();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.PrimaryExpression <em>Primary Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary Expression</em>'.
   * @see su.nsk.iae.tempor.tempor.PrimaryExpression
   * @generated
   */
  EClass getPrimaryExpression();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.PrimaryExpression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see su.nsk.iae.tempor.tempor.PrimaryExpression#getName()
   * @see #getPrimaryExpression()
   * @generated
   */
  EReference getPrimaryExpression_Name();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.PrimaryExpression#getConstant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Constant</em>'.
   * @see su.nsk.iae.tempor.tempor.PrimaryExpression#getConstant()
   * @see #getPrimaryExpression()
   * @generated
   */
  EAttribute getPrimaryExpression_Constant();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.PrimaryExpression#getTau <em>Tau</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tau</em>'.
   * @see su.nsk.iae.tempor.tempor.PrimaryExpression#getTau()
   * @see #getPrimaryExpression()
   * @generated
   */
  EReference getPrimaryExpression_Tau();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.PrimaryExpression#getNestExpr <em>Nest Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nest Expr</em>'.
   * @see su.nsk.iae.tempor.tempor.PrimaryExpression#getNestExpr()
   * @see #getPrimaryExpression()
   * @generated
   */
  EReference getPrimaryExpression_NestExpr();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.ReqDeclaration <em>Req Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Req Declaration</em>'.
   * @see su.nsk.iae.tempor.tempor.ReqDeclaration
   * @generated
   */
  EClass getReqDeclaration();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.ReqDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see su.nsk.iae.tempor.tempor.ReqDeclaration#getName()
   * @see #getReqDeclaration()
   * @generated
   */
  EAttribute getReqDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.ReqDeclaration#getRequirement <em>Requirement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Requirement</em>'.
   * @see su.nsk.iae.tempor.tempor.ReqDeclaration#getRequirement()
   * @see #getReqDeclaration()
   * @generated
   */
  EReference getReqDeclaration_Requirement();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Requirement <em>Requirement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Requirement</em>'.
   * @see su.nsk.iae.tempor.tempor.Requirement
   * @generated
   */
  EClass getRequirement();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Requirement#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Trigger</em>'.
   * @see su.nsk.iae.tempor.tempor.Requirement#getTrigger()
   * @see #getRequirement()
   * @generated
   */
  EReference getRequirement_Trigger();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Requirement#getInvariant <em>Invariant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Invariant</em>'.
   * @see su.nsk.iae.tempor.tempor.Requirement#getInvariant()
   * @see #getRequirement()
   * @generated
   */
  EReference getRequirement_Invariant();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Trig <em>Trig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trig</em>'.
   * @see su.nsk.iae.tempor.tempor.Trig
   * @generated
   */
  EClass getTrig();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.Trig#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see su.nsk.iae.tempor.tempor.Trig#getName()
   * @see #getTrig()
   * @generated
   */
  EReference getTrig_Name();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Trig#getInvariant <em>Invariant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Invariant</em>'.
   * @see su.nsk.iae.tempor.tempor.Trig#getInvariant()
   * @see #getTrig()
   * @generated
   */
  EReference getTrig_Invariant();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Trig#getRelease_reaction <em>Release reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Release reaction</em>'.
   * @see su.nsk.iae.tempor.tempor.Trig#getRelease_reaction()
   * @see #getTrig()
   * @generated
   */
  EReference getTrig_Release_reaction();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Trig#getDelay_final <em>Delay final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delay final</em>'.
   * @see su.nsk.iae.tempor.tempor.Trig#getDelay_final()
   * @see #getTrig()
   * @generated
   */
  EReference getTrig_Delay_final();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Inv <em>Inv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inv</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv
   * @generated
   */
  EClass getInv();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.Inv#getInv <em>Inv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Inv</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv#getInv()
   * @see #getInv()
   * @generated
   */
  EReference getInv_Inv();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Inv#getDelay_final <em>Delay final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delay final</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv#getDelay_final()
   * @see #getInv()
   * @generated
   */
  EReference getInv_Delay_final();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Inv#getRelease_reaction <em>Release reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Release reaction</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv#getRelease_reaction()
   * @see #getInv()
   * @generated
   */
  EReference getInv_Release_reaction();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Inv_always <em>Inv always</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inv always</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv_always
   * @generated
   */
  EClass getInv_always();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.Inv_always#getInv <em>Inv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Inv</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv_always#getInv()
   * @see #getInv_always()
   * @generated
   */
  EReference getInv_always_Inv();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.Inv_always#getRelease_reaction <em>Release reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Release reaction</em>'.
   * @see su.nsk.iae.tempor.tempor.Inv_always#getRelease_reaction()
   * @see #getInv_always()
   * @generated
   */
  EReference getInv_always_Release_reaction();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.RelRea <em>Rel Rea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rel Rea</em>'.
   * @see su.nsk.iae.tempor.tempor.RelRea
   * @generated
   */
  EClass getRelRea();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.RelRea#getReaction <em>Reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reaction</em>'.
   * @see su.nsk.iae.tempor.tempor.RelRea#getReaction()
   * @see #getRelRea()
   * @generated
   */
  EReference getRelRea_Reaction();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.RelRea#getDelay_final <em>Delay final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delay final</em>'.
   * @see su.nsk.iae.tempor.tempor.RelRea#getDelay_final()
   * @see #getRelRea()
   * @generated
   */
  EReference getRelRea_Delay_final();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Rea <em>Rea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rea</em>'.
   * @see su.nsk.iae.tempor.tempor.Rea
   * @generated
   */
  EClass getRea();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.Rea#getRea <em>Rea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Rea</em>'.
   * @see su.nsk.iae.tempor.tempor.Rea#getRea()
   * @see #getRea()
   * @generated
   */
  EReference getRea_Rea();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.DelFin <em>Del Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Del Fin</em>'.
   * @see su.nsk.iae.tempor.tempor.DelFin
   * @generated
   */
  EClass getDelFin();

  /**
   * Returns the meta object for the containment reference '{@link su.nsk.iae.tempor.tempor.DelFin#getDelay <em>Delay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delay</em>'.
   * @see su.nsk.iae.tempor.tempor.DelFin#getDelay()
   * @see #getDelFin()
   * @generated
   */
  EReference getDelFin_Delay();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.DelFin#getFin <em>Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fin</em>'.
   * @see su.nsk.iae.tempor.tempor.DelFin#getFin()
   * @see #getDelFin()
   * @generated
   */
  EReference getDelFin_Fin();

  /**
   * Returns the meta object for the attribute '{@link su.nsk.iae.tempor.tempor.DelFin#isImm <em>Imm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imm</em>'.
   * @see su.nsk.iae.tempor.tempor.DelFin#isImm()
   * @see #getDelFin()
   * @generated
   */
  EAttribute getDelFin_Imm();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Delay <em>Delay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delay</em>'.
   * @see su.nsk.iae.tempor.tempor.Delay
   * @generated
   */
  EClass getDelay();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.Delay#getDel <em>Del</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Del</em>'.
   * @see su.nsk.iae.tempor.tempor.Delay#getDel()
   * @see #getDelay()
   * @generated
   */
  EReference getDelay_Del();

  /**
   * Returns the meta object for class '{@link su.nsk.iae.tempor.tempor.Rel <em>Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rel</em>'.
   * @see su.nsk.iae.tempor.tempor.Rel
   * @generated
   */
  EClass getRel();

  /**
   * Returns the meta object for the reference '{@link su.nsk.iae.tempor.tempor.Rel#getRel <em>Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Rel</em>'.
   * @see su.nsk.iae.tempor.tempor.Rel#getRel()
   * @see #getRel()
   * @generated
   */
  EReference getRel_Rel();

  /**
   * Returns the meta object for enum '{@link su.nsk.iae.tempor.tempor.EquOperator <em>Equ Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Equ Operator</em>'.
   * @see su.nsk.iae.tempor.tempor.EquOperator
   * @generated
   */
  EEnum getEquOperator();

  /**
   * Returns the meta object for enum '{@link su.nsk.iae.tempor.tempor.CompOperator <em>Comp Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comp Operator</em>'.
   * @see su.nsk.iae.tempor.tempor.CompOperator
   * @generated
   */
  EEnum getCompOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TemporFactory getTemporFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.ModelImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Decl Var Input</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECL_VAR_INPUT = eINSTANCE.getModel_DeclVarInput();

    /**
     * The meta object literal for the '<em><b>Decl Var Output</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECL_VAR_OUTPUT = eINSTANCE.getModel_DeclVarOutput();

    /**
     * The meta object literal for the '<em><b>Sent Declaration</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SENT_DECLARATION = eINSTANCE.getModel_SentDeclaration();

    /**
     * The meta object literal for the '<em><b>Req Declaration</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REQ_DECLARATION = eINSTANCE.getModel_ReqDeclaration();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.DeclVarInputImpl <em>Decl Var Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.DeclVarInputImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDeclVarInput()
     * @generated
     */
    EClass DECL_VAR_INPUT = eINSTANCE.getDeclVarInput();

    /**
     * The meta object literal for the '<em><b>Var Decls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECL_VAR_INPUT__VAR_DECLS = eINSTANCE.getDeclVarInput_VarDecls();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.DeclVarOutputImpl <em>Decl Var Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.DeclVarOutputImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDeclVarOutput()
     * @generated
     */
    EClass DECL_VAR_OUTPUT = eINSTANCE.getDeclVarOutput();

    /**
     * The meta object literal for the '<em><b>Var Decls</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECL_VAR_OUTPUT__VAR_DECLS = eINSTANCE.getDeclVarOutput_VarDecls();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.VarDeclarationImpl <em>Var Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.VarDeclarationImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getVarDeclaration()
     * @generated
     */
    EClass VAR_DECLARATION = eINSTANCE.getVarDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECLARATION__NAME = eINSTANCE.getVarDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECLARATION__TYPE = eINSTANCE.getVarDeclaration_Type();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.SentDeclarationImpl <em>Sent Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.SentDeclarationImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getSentDeclaration()
     * @generated
     */
    EClass SENT_DECLARATION = eINSTANCE.getSentDeclaration();

    /**
     * The meta object literal for the '<em><b>Declaration Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENT_DECLARATION__DECLARATION_NAME = eINSTANCE.getSentDeclaration_DeclarationName();

    /**
     * The meta object literal for the '<em><b>Sentence Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENT_DECLARATION__SENTENCE_DECLARATION = eINSTANCE.getSentDeclaration_SentenceDeclaration();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.SentenceDeclarationImpl <em>Sentence Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.SentenceDeclarationImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getSentenceDeclaration()
     * @generated
     */
    EClass SENTENCE_DECLARATION = eINSTANCE.getSentenceDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENTENCE_DECLARATION__NAME = eINSTANCE.getSentenceDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Logic Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENTENCE_DECLARATION__LOGIC_EXPRESSION = eINSTANCE.getSentenceDeclaration_LogicExpression();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.ExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LEFT = eINSTANCE.getExpression_Left();

    /**
     * The meta object literal for the '<em><b>Or Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OR_OP = eINSTANCE.getExpression_OrOp();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RIGHT = eINSTANCE.getExpression_Right();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.XorExpressionImpl <em>Xor Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.XorExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getXorExpression()
     * @generated
     */
    EClass XOR_EXPRESSION = eINSTANCE.getXorExpression();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.AndExpressionImpl <em>And Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.AndExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getAndExpression()
     * @generated
     */
    EClass AND_EXPRESSION = eINSTANCE.getAndExpression();

    /**
     * The meta object literal for the '<em><b>And Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AND_EXPRESSION__AND_OP = eINSTANCE.getAndExpression_AndOp();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.CompExpressionImpl <em>Comp Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.CompExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getCompExpression()
     * @generated
     */
    EClass COMP_EXPRESSION = eINSTANCE.getCompExpression();

    /**
     * The meta object literal for the '<em><b>Comp Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMP_EXPRESSION__COMP_OP = eINSTANCE.getCompExpression_CompOp();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.EquExpressionImpl <em>Equ Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.EquExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getEquExpression()
     * @generated
     */
    EClass EQU_EXPRESSION = eINSTANCE.getEquExpression();

    /**
     * The meta object literal for the '<em><b>Equ Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQU_EXPRESSION__EQU_OP = eINSTANCE.getEquExpression_EquOp();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.UnExpressionImpl <em>Un Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.UnExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getUnExpression()
     * @generated
     */
    EClass UN_EXPRESSION = eINSTANCE.getUnExpression();

    /**
     * The meta object literal for the '<em><b>Un Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UN_EXPRESSION__UN_OP = eINSTANCE.getUnExpression_UnOp();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.TauExpressionImpl <em>Tau Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.TauExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getTauExpression()
     * @generated
     */
    EClass TAU_EXPRESSION = eINSTANCE.getTauExpression();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAU_EXPRESSION__TIME = eINSTANCE.getTauExpression_Time();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.TimeLiteralImpl <em>Time Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.TimeLiteralImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getTimeLiteral()
     * @generated
     */
    EClass TIME_LITERAL = eINSTANCE.getTimeLiteral();

    /**
     * The meta object literal for the '<em><b>Interval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_LITERAL__INTERVAL = eINSTANCE.getTimeLiteral_Interval();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.PrimaryExpressionImpl <em>Primary Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.PrimaryExpressionImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getPrimaryExpression()
     * @generated
     */
    EClass PRIMARY_EXPRESSION = eINSTANCE.getPrimaryExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMARY_EXPRESSION__NAME = eINSTANCE.getPrimaryExpression_Name();

    /**
     * The meta object literal for the '<em><b>Constant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMARY_EXPRESSION__CONSTANT = eINSTANCE.getPrimaryExpression_Constant();

    /**
     * The meta object literal for the '<em><b>Tau</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMARY_EXPRESSION__TAU = eINSTANCE.getPrimaryExpression_Tau();

    /**
     * The meta object literal for the '<em><b>Nest Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMARY_EXPRESSION__NEST_EXPR = eINSTANCE.getPrimaryExpression_NestExpr();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.ReqDeclarationImpl <em>Req Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.ReqDeclarationImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getReqDeclaration()
     * @generated
     */
    EClass REQ_DECLARATION = eINSTANCE.getReqDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQ_DECLARATION__NAME = eINSTANCE.getReqDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Requirement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQ_DECLARATION__REQUIREMENT = eINSTANCE.getReqDeclaration_Requirement();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.RequirementImpl <em>Requirement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.RequirementImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRequirement()
     * @generated
     */
    EClass REQUIREMENT = eINSTANCE.getRequirement();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENT__TRIGGER = eINSTANCE.getRequirement_Trigger();

    /**
     * The meta object literal for the '<em><b>Invariant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIREMENT__INVARIANT = eINSTANCE.getRequirement_Invariant();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.TrigImpl <em>Trig</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.TrigImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getTrig()
     * @generated
     */
    EClass TRIG = eINSTANCE.getTrig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIG__NAME = eINSTANCE.getTrig_Name();

    /**
     * The meta object literal for the '<em><b>Invariant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIG__INVARIANT = eINSTANCE.getTrig_Invariant();

    /**
     * The meta object literal for the '<em><b>Release reaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIG__RELEASE_REACTION = eINSTANCE.getTrig_Release_reaction();

    /**
     * The meta object literal for the '<em><b>Delay final</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIG__DELAY_FINAL = eINSTANCE.getTrig_Delay_final();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.InvImpl <em>Inv</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.InvImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getInv()
     * @generated
     */
    EClass INV = eINSTANCE.getInv();

    /**
     * The meta object literal for the '<em><b>Inv</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INV__INV = eINSTANCE.getInv_Inv();

    /**
     * The meta object literal for the '<em><b>Delay final</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INV__DELAY_FINAL = eINSTANCE.getInv_Delay_final();

    /**
     * The meta object literal for the '<em><b>Release reaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INV__RELEASE_REACTION = eINSTANCE.getInv_Release_reaction();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.Inv_alwaysImpl <em>Inv always</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.Inv_alwaysImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getInv_always()
     * @generated
     */
    EClass INV_ALWAYS = eINSTANCE.getInv_always();

    /**
     * The meta object literal for the '<em><b>Inv</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INV_ALWAYS__INV = eINSTANCE.getInv_always_Inv();

    /**
     * The meta object literal for the '<em><b>Release reaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INV_ALWAYS__RELEASE_REACTION = eINSTANCE.getInv_always_Release_reaction();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.RelReaImpl <em>Rel Rea</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.RelReaImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRelRea()
     * @generated
     */
    EClass REL_REA = eINSTANCE.getRelRea();

    /**
     * The meta object literal for the '<em><b>Reaction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REL_REA__REACTION = eINSTANCE.getRelRea_Reaction();

    /**
     * The meta object literal for the '<em><b>Delay final</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REL_REA__DELAY_FINAL = eINSTANCE.getRelRea_Delay_final();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.ReaImpl <em>Rea</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.ReaImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRea()
     * @generated
     */
    EClass REA = eINSTANCE.getRea();

    /**
     * The meta object literal for the '<em><b>Rea</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REA__REA = eINSTANCE.getRea_Rea();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.DelFinImpl <em>Del Fin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.DelFinImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDelFin()
     * @generated
     */
    EClass DEL_FIN = eINSTANCE.getDelFin();

    /**
     * The meta object literal for the '<em><b>Delay</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEL_FIN__DELAY = eINSTANCE.getDelFin_Delay();

    /**
     * The meta object literal for the '<em><b>Fin</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEL_FIN__FIN = eINSTANCE.getDelFin_Fin();

    /**
     * The meta object literal for the '<em><b>Imm</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEL_FIN__IMM = eINSTANCE.getDelFin_Imm();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.DelayImpl <em>Delay</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.DelayImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getDelay()
     * @generated
     */
    EClass DELAY = eINSTANCE.getDelay();

    /**
     * The meta object literal for the '<em><b>Del</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELAY__DEL = eINSTANCE.getDelay_Del();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.impl.RelImpl <em>Rel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.impl.RelImpl
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getRel()
     * @generated
     */
    EClass REL = eINSTANCE.getRel();

    /**
     * The meta object literal for the '<em><b>Rel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REL__REL = eINSTANCE.getRel_Rel();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.EquOperator <em>Equ Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.EquOperator
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getEquOperator()
     * @generated
     */
    EEnum EQU_OPERATOR = eINSTANCE.getEquOperator();

    /**
     * The meta object literal for the '{@link su.nsk.iae.tempor.tempor.CompOperator <em>Comp Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see su.nsk.iae.tempor.tempor.CompOperator
     * @see su.nsk.iae.tempor.tempor.impl.TemporPackageImpl#getCompOperator()
     * @generated
     */
    EEnum COMP_OPERATOR = eINSTANCE.getCompOperator();

  }

} //TemporPackage
