/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trig</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.tempor.tempor.Trig#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.Trig#getInvariant <em>Invariant</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.Trig#getRelease_reaction <em>Release reaction</em>}</li>
 *   <li>{@link su.nsk.iae.tempor.tempor.Trig#getDelay_final <em>Delay final</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getTrig()
 * @model
 * @generated
 */
public interface Trig extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(SentenceDeclaration)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getTrig_Name()
   * @model
   * @generated
   */
  SentenceDeclaration getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.Trig#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(SentenceDeclaration value);

  /**
   * Returns the value of the '<em><b>Invariant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariant</em>' containment reference.
   * @see #setInvariant(Inv)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getTrig_Invariant()
   * @model containment="true"
   * @generated
   */
  Inv getInvariant();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.Trig#getInvariant <em>Invariant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invariant</em>' containment reference.
   * @see #getInvariant()
   * @generated
   */
  void setInvariant(Inv value);

  /**
   * Returns the value of the '<em><b>Release reaction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Release reaction</em>' containment reference.
   * @see #setRelease_reaction(RelRea)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getTrig_Release_reaction()
   * @model containment="true"
   * @generated
   */
  RelRea getRelease_reaction();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.Trig#getRelease_reaction <em>Release reaction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Release reaction</em>' containment reference.
   * @see #getRelease_reaction()
   * @generated
   */
  void setRelease_reaction(RelRea value);

  /**
   * Returns the value of the '<em><b>Delay final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay final</em>' containment reference.
   * @see #setDelay_final(DelFin)
   * @see su.nsk.iae.tempor.tempor.TemporPackage#getTrig_Delay_final()
   * @model containment="true"
   * @generated
   */
  DelFin getDelay_final();

  /**
   * Sets the value of the '{@link su.nsk.iae.tempor.tempor.Trig#getDelay_final <em>Delay final</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delay final</em>' containment reference.
   * @see #getDelay_final()
   * @generated
   */
  void setDelay_final(DelFin value);

} // Trig
