/**
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.tempor;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xor Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.tempor.tempor.TemporPackage#getXorExpression()
 * @model
 * @generated
 */
public interface XorExpression extends Expression
{
} // XorExpression
