/*
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import su.nsk.iae.tempor.TemporRuntimeModule;
import su.nsk.iae.tempor.TemporStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TemporIdeSetup extends TemporStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TemporRuntimeModule(), new TemporIdeModule()));
	}
	
}
