/*
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTemporScopeProvider extends DelegatingScopeProvider {
}
