/*
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TemporAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("su/nsk/iae/tempor/parser/antlr/internal/InternalTempor.tokens");
	}
}
