/*
 * generated by Xtext 2.30.0
 */
package su.nsk.iae.tempor.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTemporValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(su.nsk.iae.tempor.tempor.TemporPackage.eINSTANCE);
		return result;
	}
}
